apiVersion: "nuclio.io/v1beta1"
kind: "Function"
spec:
  HTTPPort: 36543
  env:
    - name: PGINFO
      value: some_postgres_username:some_password@some_host:some_port
  runtime: "python"
  handler: "database_init:handler"
  build:
    commands:
    - "apk update && apk add --virtual build-deps gcc python-dev musl-dev && apk add postgresql-dev"
    - "pip install psycopg2 parse requests"
