apiVersion: "nuclio.io/v1beta1"
kind: "Function"
spec:
  env:
    - name: PGUSERNAME
      value: some_postgres_username
    - name: PGPASSWORD
      value: some_password
    - name: PGHOST
      value: some_host
    - name: PGPORT
      value: some_port
    - name: USERS
      value: githubusername1_slackusername1_guthubusername2_slackusername2
  runtime: "python"
  handler: "database_init:handler"
  build:
    commands:
    - "apk update"
    - "apk add --virtual build-deps gcc python-dev musl-dev"
    - "apk add postgresql-dev"
    - "pip install psycopg2"
