apiVersion: "nuclio.io/v1beta1"
kind: "Function"
spec:
  httpPort: 36548
  env:
    - name: PGINFO
      value: postgres:pass@172.17.0.1:5432
  runtime: "python"
  handler: "test_complete:handler"
  build:
    commands:
    - "apk update && apk add --virtual build-deps gcc python-dev musl-dev && apk add postgresql-dev"
    - "pip install psycopg2 parse requests"
