apiVersion: "nuclio.io/v1beta1"
kind: "Function"
spec:
  env:
    - name: HOST_URL
      value: localhost:5000
    - name: DOCKERIZED_BUILD
      value: TRUE
  runtime: "python:3.6"
  handler: "build_push_artifacts:handler"
  build:
    baseImage: jessie
    commands:
      - "apt-get update && apt-get install -y git && apt-get install -y build-essential && apt-get install make"
      - "pip install parse delegator.py"
