apiVersion: "nuclio.io/v1beta1"
kind: "Function"
spec:
  env:
    - name: HOST_URL
      value: localhost:5000
    - name: DOCKERIZED_BUILD
      value: TRUE
    - name: GOPATH
      value: /root/go
    - name: NUCLIO_PATH
      value: /root/go/src/github.com/nuclio/nuclio
  runtime: "python:3.6"
  handler: "build_push_artifacts:handler"
  build:
    baseImage: jessie
    commands:
      - "export PATH=$PATH:/usr/local/go/bin && apt-get update && apt-get install -y git"
      - "export PATH=$PATH:/usr/local/go/bin && apt-get install -y build-essential && curl -O https://download.docker.com/linux/static/stable/x86_64/docker-18.03.0-ce.tgz"
      - "export PATH=$PATH:/usr/local/go/bin && tar xzvf docker-18.03.0-ce.tgz"
      - "export PATH=$PATH:/usr/local/go/bin && cp docker/* /usr/bin/"
      - "export PATH=$PATH:/usr/local/go/bin && curl -O https://dl.google.com/go/go1.9.5.linux-amd64.tar.gz"
      - "export PATH=$PATH:/usr/local/go/bin && tar -C /usr/local -xzf go1.9.5.linux-amd64.tar.gz"
      - "export PATH=$PATH:/usr/local/go/bin && mkdir -p $NUCLIO_PATH && go get github.com/v3io/v3io-go-http/..."
      - "export PATH=$PATH:/usr/local/go/bin && go get github.com/nuclio/logger/..."
      - "export PATH=$PATH:/usr/local/go/bin && go get github.com/nuclio/nuclio-sdk-go/..."
      - "export PATH=$PATH:/usr/local/go/bin && go get github.com/nuclio/amqp/... "
      - "pip install parse delegator.py"
